# Description of what this change includes
# Revision number 1
# Date Aug 19, 2025
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create a VPC named VPC-noread8342 in us-west-2
  with subnets spanning 3 Availability Zones.

Parameters:
  VPCCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

  PublicSubnetCidr1:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for Public Subnet 1

  PublicSubnetCidr2:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for Public Subnet 2

  PublicSubnetCidr3:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR block for Public Subnet 3

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: VPC-noread8342

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW-noread8342

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr1
      AvailabilityZone: !Select [0, !GetAZs us-west-2]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet1-noread8342

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr2
      AvailabilityZone: !Select [1, !GetAZs us-west-2]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet2-noread8342

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr3
      AvailabilityZone: !Select [2, !GetAZs us-west-2]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet3-noread8342

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Public-RT-noread8342

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  SubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet3
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Description: The ID of the new VPC
    Value: !Ref MyVPC
  Subnet1Id:
    Description: The ID of Public Subnet 1
    Value: !Ref PublicSubnet1
  Subnet2Id:
    Description: The ID of Public Subnet 2
    Value: !Ref PublicSubnet2
  Subnet3Id:
    Description: The ID of Public Subnet 3
    Value: !Ref PublicSubnet3
